# Generated by nativegate. Do not edit by hand — re-run `ngate generate`.
"""The MCP view of this service exposes usable tools."""
import pytest

fastmcp = pytest.importorskip("fastmcp")

from specfun.mcp_server import mcp  # noqa: E402
from specfun.router import router  # noqa: E402


def _post_routes():
    return [
        route
        for route in router.routes
        if "POST" in getattr(route, "methods", set())
    ]


@pytest.mark.anyio
async def test_every_post_route_becomes_a_named_tool():
    async with fastmcp.Client(mcp) as client:
        tools = {tool.name for tool in await client.list_tools()}

    # The tool name is the route's operation_id, which is the native symbol
    # name. If this fails with names like "foo_endpoint_foo_post", the
    # operation_id= on the generated route decorator was lost — the tools
    # still work, but the model sees mangled names.
    for route in _post_routes():
        assert route.operation_id in tools, (
            f"route {route.path} produced no tool named "
            f"{route.operation_id!r}; got {sorted(tools)}"
        )


@pytest.mark.anyio
async def test_every_tool_has_a_description():
    async with fastmcp.Client(mcp) as client:
        undescribed = [t.name for t in await client.list_tools() if not t.description]
    # FastMCP falls back to a title-cased function name when a route has no
    # docstring, so an empty description means the generated docstring is gone.
    assert not undescribed, f"tools with no description: {undescribed}"


@pytest.fixture
def anyio_backend():
    return "asyncio"
