# Generated by nativegate. Do not edit by hand — re-run `ngate test`.
# Extend with real assertions; this is a build/import smoke test.

def test_DLGAMA_importable():
    from specfun import DLGAMA

    DLGAMA(1.0)

def test_DAW_importable():
    from specfun import DAW

    DAW(1.0)

def test_EI_importable():
    from specfun import EI

    EI(1.0)

def test_EONE_importable():
    from specfun import EONE

    EONE(1.0)

def test_EXPEI_importable():
    from specfun import EXPEI

    EXPEI(1.0)

def test_DERF_importable():
    from specfun import DERF

    DERF(1.0)

def test_DERFC_importable():
    from specfun import DERFC

    DERFC(1.0)

def test_DERFCX_importable():
    from specfun import DERFCX

    DERFCX(1.0)

def test_DGAMMA_importable():
    from specfun import DGAMMA

    DGAMMA(1.0)

def test_BESI0_importable():
    from specfun import BESI0

    BESI0(1.0)

def test_BESI1_importable():
    from specfun import BESI1

    BESI1(1.0)

def test_BESK0_importable():
    from specfun import BESK0

    BESK0(1.0)

def test_BESK1_importable():
    from specfun import BESK1

    BESK1(1.0)

def test_PSI_importable():
    from specfun import PSI

    PSI(1.0)
