# Generated by nativegate. Do not edit by hand — re-run `ngate generate`.
from ._native.specfun import dlgama as DLGAMA, daw as DAW, ei as EI, eone as EONE, expei as EXPEI, derf as DERF, derfc as DERFC, derfcx as DERFCX, dgamma as DGAMMA, besi0 as BESI0, besi1 as BESI1, besk0 as BESK0, besk1 as BESK1, psi as PSI

__all__ = ["DLGAMA", "DAW", "EI", "EONE", "EXPEI", "DERF", "DERFC", "DERFCX", "DGAMMA", "BESI0", "BESI1", "BESK0", "BESK1", "PSI"]
