# Generated by nativegate. Do not edit by hand — re-run `ngate generate`.
import threading
from fastapi import APIRouter

from . import DLGAMA, DAW, EI, EONE, EXPEI, DERF, DERFC, DERFCX, DGAMMA, BESI0, BESI1, BESK0, BESK1, PSI

# Every native call below is serialised through this one process-wide lock.
#
# Fortran COMMON blocks are process-global storage, not per-call state. A
# routine like PVTINI writes COMMON /FLUID/ and a later call to PVTRS,
# PVTBO or PVTVIS reads it back — the header's own contract is "CALL
# PVTSET(P) THEN USE THE COMMON". FastAPI runs synchronous `def` endpoints
# in a threadpool, so without this lock two requests configuring different
# fluids interleave their writes and reads in the SAME COMMON block and
# each caller gets numbers computed from the other caller's fluid. Nothing
# raises, nothing logs; the answers are just wrong.
#
# Per-request objects cannot fix this the way they fix a stateful C++ class:
# COMMON is reachable from every instance because it belongs to the process.
#
# DO NOT REMOVE THIS TO IMPROVE THROUGHPUT. It caps native execution at one
# concurrent call per process on purpose. The supported ways to go faster are
# more processes, or an API reshaped so a configure+read pair is one call.
#
# RLock, not Lock: if one generated endpoint is ever changed to call another,
# a plain Lock would deadlock the request against itself.
_NATIVE_LOCK = threading.RLock()

router = APIRouter(tags=["specfun"])

# Symbols this build recognised and refused to bind, with the reason.
#
# Refusal is nativegate's safety mechanism (a non-const char* output buffer
# has no length; a pointer return has no ownership; a derived-type Fortran
# result has no mapping), so the refusals are part of this service's
# contract and not an implementation detail. An EMPTY mapping means this
# build refused nothing; a 404 on this route means the service predates
# the feature and cannot tell you either way.
_UNEXPOSED: dict[str, str] = {
}

@router.get("/_unexposed", tags=["introspection"], operation_id="specfun_unexposed")
def _nativegate_unexposed() -> dict[str, str]:
    """Symbols the parser recognised but refused to bind, and why."""
    return _UNEXPOSED

@router.post("/DLGAMA", operation_id="specfun_DLGAMA")
def DLGAMA_endpoint(X: float):
    """This routine calculates the LOG(GAMMA) function for a positive real
    argument X.  Computation is based on an algorithm outlined in
    references 1 and 2.  The program uses rational functions that
    theoretically approximate LOG(GAMMA) to at least 18 significant
    decimal digits.  The approximation for X > 12 is from reference
    3, while approximations for X < 12.0 are similar to those in
    reference 1, but are unpublished.  The accuracy achieved depends
    on the arithmetic system, the compiler, the intrinsic functions,
    and proper selection of the machine-dependent constants.
    Explanation of machine-dependent constants
    beta   - radix for the floating-point representation
    maxexp - the smallest positive power of beta that overflows
    XBIG   - largest argument for which LN(GAMMA(X)) is representable
    in the machine, i.e., the solution to the equation
    LN(GAMMA(XBIG)) = beta**maxexp
    XINF   - largest machine representable floating-point number;
    approximately beta**maxexp.
    EPS    - The smallest positive floating-point number such that
    1.0+EPS .GT. 1.0
    FRTBIG - Rough estimate of the fourth root of XBIG
    Approximate values for some important machines are:
    beta      maxexp         XBIG
    CRAY-1        (S.P.)        2        8191       9.62E+2461
    Cyber 180/855
    under NOS   (S.P.)        2        1070       1.72E+319
    IEEE (IBM/XT,
    SUN, etc.)  (S.P.)        2         128       4.08E+36
    IEEE (IBM/XT,
    SUN, etc.)  (D.P.)        2        1024       2.55D+305
    IBM 3033      (D.P.)       16          63       4.29D+73

    Call the native routine `DLGAMA`.
    """
    with _NATIVE_LOCK:
        result = DLGAMA(X)
    return {"result": result}

@router.post("/DAW", operation_id="specfun_DAW")
def DAW_endpoint(XX: float):
    """This function program evaluates Dawson's integral,
    2  / x   2
    -x   |    t
    F(x) = e     |   e    dt
    / 0
    for a real argument x.
    The calling sequence for this function is
    Y=DAW(X)
    The main computation uses rational Chebyshev approximations
    published in Math. Comp. 24, 171-178 (1970) by Cody, Paciorek
    and Thacher.  This transportable program is patterned after the
    machine-dependent FUNPACK program DDAW(X), but cannot match that
    version for efficiency or accuracy.  This version uses rational
    approximations that are theoretically accurate to about 19
    significant decimal digits.  The accuracy achieved depends on the
    arithmetic system, the compiler, the intrinsic functions, and
    proper selection of the machine-dependent constants.
    Explanation of machine-dependent constants
    XINF   = largest positive machine number
    XMIN   = the smallest positive machine number.
    EPS    = smallest positive number such that 1+eps > 1.
    Approximately  beta**(-p), where beta is the machine
    radix and p is the number of significant base-beta
    digits in a floating-point number.
    XMAX   = absolute argument beyond which DAW(X) underflows.
    XMAX = min(0.5/xmin, xinf).
    XSMALL = absolute argument below DAW(X)  may be represented
    by X.  We recommend XSMALL = sqrt(eps).
    XLARGE = argument beyond which DAW(X) may be represented by
    1/(2x).  We recommend XLARGE = 1/sqrt(eps).

    Call the native routine `DAW`.
    """
    with _NATIVE_LOCK:
        result = DAW(XX)
    return {"result": result}

@router.post("/EI", operation_id="specfun_EI")
def EI_endpoint(X: float):
    """This function program computes approximate values for the
    exponential integral  Ei(x), where  x  is real.
    Author: W. J. Cody
    Latest modification: January 12, 1988

    Call the native routine `EI`.
    """
    with _NATIVE_LOCK:
        result = EI(X)
    return {"result": result}

@router.post("/EONE", operation_id="specfun_EONE")
def EONE_endpoint(X: float):
    """This function program computes approximate values for the
    exponential integral E1(x), where  x  is real.
    Author: W. J. Cody
    Latest modification: January 12, 1988

    Call the native routine `EONE`.
    """
    with _NATIVE_LOCK:
        result = EONE(X)
    return {"result": result}

@router.post("/EXPEI", operation_id="specfun_EXPEI")
def EXPEI_endpoint(X: float):
    """This function program computes approximate values for the
    function  exp(-x) * Ei(x), where  Ei(x)  is the exponential
    integral, and  x  is real.
    Author: W. J. Cody
    Latest modification: January 12, 1988

    Call the native routine `EXPEI`.
    """
    with _NATIVE_LOCK:
        result = EXPEI(X)
    return {"result": result}

@router.post("/DERF", operation_id="specfun_DERF")
def DERF_endpoint(X: float):
    """This subprogram computes approximate values for erf(x).
    (see comments heading CALERF).
    Author/date: W. J. Cody, January 8, 1985

    Call the native routine `DERF`.
    """
    with _NATIVE_LOCK:
        result = DERF(X)
    return {"result": result}

@router.post("/DERFC", operation_id="specfun_DERFC")
def DERFC_endpoint(X: float):
    """This subprogram computes approximate values for erfc(x).
    (see comments heading CALERF).
    Author/date: W. J. Cody, January 8, 1985

    Call the native routine `DERFC`.
    """
    with _NATIVE_LOCK:
        result = DERFC(X)
    return {"result": result}

@router.post("/DERFCX", operation_id="specfun_DERFCX")
def DERFCX_endpoint(X: float):
    """This subprogram computes approximate values for exp(x*x) * erfc(x).
    (see comments heading CALERF).
    Author/date: W. J. Cody, March 30, 1987

    Call the native routine `DERFCX`.
    """
    with _NATIVE_LOCK:
        result = DERFCX(X)
    return {"result": result}

@router.post("/DGAMMA", operation_id="specfun_DGAMMA")
def DGAMMA_endpoint(X: float):
    """This routine calculates the GAMMA function for a real argument X.
    Computation is based on an algorithm outlined in reference 1.
    The program uses rational functions that approximate the GAMMA
    function to at least 20 significant decimal digits.  Coefficients
    for the approximation over the interval (1,2) are unpublished.
    Those for the approximation for X .GE. 12 are from reference 2.
    The accuracy achieved depends on the arithmetic system, the
    compiler, the intrinsic functions, and proper selection of the
    machine-dependent constants.
    Explanation of machine-dependent constants
    beta   - radix for the floating-point representation
    maxexp - the smallest positive power of beta that overflows
    XBIG   - the largest argument for which GAMMA(X) is representable
    in the machine, i.e., the solution to the equation
    GAMMA(XBIG) = beta**maxexp
    XINF   - the largest machine representable floating-point number;
    approximately beta**maxexp
    EPS    - the smallest positive floating-point number such that
    1.0+EPS .GT. 1.0
    XMININ - the smallest positive floating-point number such that
    1/XMININ is machine representable
    Approximate values for some important machines are:
    beta       maxexp        XBIG
    CRAY-1         (S.P.)        2         8191        966.961
    Cyber 180/855
    under NOS    (S.P.)        2         1070        177.803
    IEEE (IBM/XT,
    SUN, etc.)   (S.P.)        2          128        35.040
    IEEE (IBM/XT,
    SUN, etc.)   (D.P.)        2         1024        171.624

    Call the native routine `DGAMMA`.
    """
    with _NATIVE_LOCK:
        result = DGAMMA(X)
    return {"result": result}

@router.post("/BESI0", operation_id="specfun_BESI0")
def BESI0_endpoint(X: float):
    """This long precision subprogram computes approximate values for
    modified Bessel functions of the first kind of order zero for
    arguments ABS(ARG) .LE. XMAX  (see comments heading CALCI0).

    Call the native routine `BESI0`.
    """
    with _NATIVE_LOCK:
        result = BESI0(X)
    return {"result": result}

@router.post("/BESI1", operation_id="specfun_BESI1")
def BESI1_endpoint(X: float):
    """This long precision subprogram computes approximate values for
    modified Bessel functions of the first kind of order one for
    arguments ABS(ARG) .LE. XMAX  (see comments heading CALCI1).

    Call the native routine `BESI1`.
    """
    with _NATIVE_LOCK:
        result = BESI1(X)
    return {"result": result}

@router.post("/BESK0", operation_id="specfun_BESK0")
def BESK0_endpoint(X: float):
    """This function program computes approximate values for the
    modified Bessel function of the second kind of order zero
    for arguments 0.0 .LT. ARG .LE. XMAX (see comments heading
    CALCK0).
    Authors: W. J. Cody and Laura Stoltz
    Latest Modification: January 19, 1988

    Call the native routine `BESK0`.
    """
    with _NATIVE_LOCK:
        result = BESK0(X)
    return {"result": result}

@router.post("/BESK1", operation_id="specfun_BESK1")
def BESK1_endpoint(X: float):
    """This function program computes approximate values for the
    modified Bessel function of the second kind of order one
    for arguments  XLEAST .LE. ARG .LE. XMAX.

    Call the native routine `BESK1`.
    """
    with _NATIVE_LOCK:
        result = BESK1(X)
    return {"result": result}

@router.post("/PSI", operation_id="specfun_PSI")
def PSI_endpoint(XX: float):
    """This function program evaluates the logarithmic derivative of the
    gamma function,
    psi(x) = d/dx (gamma(x)) / gamma(x) = d/dx (ln gamma(x))
    for real x, where either
    -xmax1 < x < -xmin (x not a negative integer), or
    xmin < x.
    The calling sequence for this function is
    Y = PSI(X)
    The main computation uses rational Chebyshev approximations
    published in Math. Comp. 27, 123-127 (1973) by Cody, Strecok and
    Thacher.  This transportable program is patterned after the
    machine-dependent FUNPACK program PSI(X), but cannot match that
    version for efficiency or accuracy.  This version uses rational
    approximations that are theoretically accurate to 20 significant
    decimal digits.  The accuracy achieved depends on the arithmetic
    system, the compiler, the intrinsic functions, and proper selection
    of the machine-dependent constants.
    Explanation of machine-dependent constants
    XINF   = largest positive machine number
    XMAX1  = beta ** (p-1), where beta is the radix for the
    floating-point system, and p is the number of base-beta
    digits in the floating-point significand.  This is an
    upper bound on non-integral floating-point numbers, and
    the negative of the lower bound on acceptable negative
    arguments for PSI.  If rounding is necessary, round this
    value down.
    XMIN1  = the smallest in magnitude acceptable argument.  We
    recommend XMIN1 = MAX(1/XINF,xmin) rounded up, where
    xmin is the smallest positive floating-point number.
    XSMALL = absolute argument below which  PI*COTAN(PI*X)  may be

    Call the native routine `PSI`.
    """
    with _NATIVE_LOCK:
        result = PSI(XX)
    return {"result": result}
