# Generated by nativegate. Do not edit by hand — re-run `ngate generate`.
import logging
import os
import uuid

from fastapi.responses import JSONResponse
from fastapi import FastAPI, Request

from .middleware import install_middleware, readiness
from .router import router
from .mcp_server import mcp_app

# `lifespan=` is not optional: FastMCP's streamable-HTTP session manager starts
# in mcp_app's lifespan, and mounting the app without adopting it fails every
# tool call at runtime with "task group was not initialized" — at request time,
# not at startup. See generators/mcp_gen.py.
app = FastAPI(title="specfun", lifespan=mcp_app.lifespan)
app.include_router(router)

# Auth, rate limiting, body-size limits, request ids and access logging. Called
# here AND in the gateway app: middleware attaches to an app, and a router
# mounted into a gateway runs under the gateway's app.
install_middleware(app, "specfun")
readiness(app, "specfun")

# The MCP view of these same endpoints, for an LLM client. Served at
# "/mcp/"; "/mcp" answers 307 to it. Auth, rate limiting and request
# ids come from the middleware installed above, because that attaches to THIS
# app and the mount sits underneath it.
app.mount("/mcp", mcp_app)


@app.get("/healthz", tags=["health"])
def healthz():
    """Liveness: the process is up and the native extension imported.

    Deliberately NOT readiness — see /readyz. A liveness probe that fails
    during startup gets the container killed and restarted forever.
    """
    return {"status": "ok", "service": "specfun"}


_LOG = logging.getLogger("nativegate.specfun")

# Off by default. A native routine's exception text can carry deck values,
# array contents or absolute paths from the build machine; none of that should
# leave the process just because something failed. Turn it on deliberately,
# in a non-production environment, when a caller needs to see why.
_DEBUG_ERRORS = os.environ.get("NATIVEGATE_DEBUG_ERRORS", "").lower() not in ("", "0", "false", "no")


@app.exception_handler(Exception)
async def _unhandled_native_error(request: Request, exc: Exception):
    """Give a failed request a JSON body and an id that matches the log line.

    Without this, Starlette answers `Internal Server Error` as plain text —
    safe, but untraceable and a second content type for clients to parse.

    HTTPException does NOT reach here — FastAPI handles it first — so the
    generated argument-validation errors keep their own status and detail.

    Caveats, both real: with `debug=True` Starlette returns its traceback
    response *instead* of this one, so do not enable debug on a deployed
    service; and a segfault, Fortran STOP or hang kills the worker process
    before any Python handler runs. See docs/production-readiness.md.
    """
    error_id = uuid.uuid4().hex[:12]
    # .exception() so the traceback reaches the log exactly once, keyed by the
    # same id the caller was given — that pairing is the whole point.
    _LOG.exception(
        "unhandled error %s on %s %s", error_id, request.method, request.url.path
    )
    body = {"error": "internal server error", "error_id": error_id}
    if _DEBUG_ERRORS:
        body["detail"] = f"{type(exc).__name__}: {exc}"
    return JSONResponse(status_code=500, content=body)
