[build-system]
requires = ["scikit-build-core", "numpy", "meson", "ninja"]
build-backend = "scikit_build_core.build"

[project]
name = "specfun"
readme = "README.md"
version = "1.0.6"
requires-python = ">=3.10"
dependencies = ["fastapi", "uvicorn", "gunicorn", "uvicorn-worker", "fastmcp", "numpy"]

[tool.scikit-build]
wheel.packages = ["python/specfun"]
cmake.source-dir = "."
